"""effect — a Python port of Effect-TS."""

from effect import (
    cause,
    concurrency,
    context,
    data,
    deferred,
    effect,
    either,
    exit,
    fiber,
    layer,
    option,
    queue,
    ref,
    runtime,
    scope,
)
from effect.cause import Cause
from effect.context import Context, GenericTag, Tag, empty, make, merge
from effect.data import TaggedError, tagged_class, tagged_error
from effect.effect import (
    AsyncFiberException,
    Deferred,
    Effect,
    Fiber,
    Queue,
    all,
    async_,
    catch_all,
    catch_if,
    catch_tag,
    deferred_make,
    fail,
    flat_map,
    fork,
    gen,
    map,
    match_effect,
    on_exit,
    pipe,
    provide,
    provide_context,
    provide_service,
    queue_make,
    run_async,
    run_async_exit,
    run_sync,
    run_sync_exit,
    succeed,
    sync,
    tag,
    tap,
    try_,
    zip,
    zip_par,
)
from effect.effect import (
    context as context_effect,
)
from effect.exit import Exit
from effect.layer import Layer, build, provide_to
from effect.layer import merge as merge_layers
from effect.layer import succeed as layer_succeed
from effect.option import Option
from effect.ref import Ref
from effect.ref import make as ref_make
from effect.runtime import Runtime, default_runtime
from effect.runtime import run_async as runtime_run_async
from effect.scope import (
    CloseableScope,
    Scope,
    acquire_release,
    add_finalizer,
    scoped,
    scoped_with,
)
from effect.scope import make as scope_make

__all__ = [
    "acquire_release",
    "add_finalizer",
    "all",
    "async_",
    "AsyncFiberException",
    "build",
    "catch_all",
    "catch_if",
    "catch_tag",
    "cause",
    "Cause",
    "CloseableScope",
    "concurrency",
    "Context",
    "context",
    "context_effect",
    "data",
    "default_runtime",
    "Deferred",
    "deferred_make",
    "deferred",
    "Effect",
    "effect",
    "either",
    "empty",
    "Exit",
    "exit",
    "fail",
    "Fiber",
    "fiber",
    "flat_map",
    "fork",
    "gen",
    "GenericTag",
    "Layer",
    "layer",
    "layer_succeed",
    "make",
    "map",
    "match_effect",
    "merge",
    "merge_layers",
    "on_exit",
    "Option",
    "option",
    "pipe",
    "provide",
    "provide_context",
    "provide_service",
    "provide_to",
    "Queue",
    "queue_make",
    "queue",
    "Ref",
    "ref",
    "ref_make",
    "run_async",
    "run_async_exit",
    "Runtime",
    "runtime",
    "runtime_run_async",
    "run_sync",
    "run_sync_exit",
    "Scope",
    "scope",
    "scope_make",
    "scoped",
    "scoped_with",
    "succeed",
    "sync",
    "Tag",
    "tag",
    "tap",
    "tagged_class",
    "tagged_error",
    "TaggedError",
    "try_",
    "zip",
    "zip_par",
]
